# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c00b3abd6d56f7fb255936c46de4dbd2d5535bfde1db328df6fcf300f25af05f09786d85cba7d2a420dd2ad6d4fcce9ec243a30e22326b3d63a838f8bd5c1514

test:
  secret_key_base: 9fe67e4dedc098642265cf3ad45fc9c2629c60dbe743aa9b4b3b12d4d5c4a5d07b57ad7d90acf17c95c4989f9e72a8bbc34d287649268f80eaa460569c26e6fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 9fe67e4dedc098642265cf3ad45fc9c2629c60dbe743aa9b4b3b12d4d5c4a5d07b57ad7d90acf17c95c4989f9e72a8bbc34d287649268f80eaa460569c26e6fa
